config/routes.rb
Rails.application.routes.draw do

  root 'messages#index'
  resources :messages , except: [:new]
  resources :answers , except: [:new]

end

app/models/answer.rb
class Answer < ActiveRecord::Base
    
    belongs_to :message
    belongs_to :user
    
    validates :name , length: {  maximum: 20 } , presence: true
    validates :age , numericality: {
            only_integer: true, greater_than_or_equal_to: 0
          }

    # 内容は必須入力かつ2文字以上30文字以下
    validates :body , length: {minimum: 2 , maximum: 140 } , presence: true
    
    
end

app/models/message.rb
class Message < ActiveRecord::Base
    
    has_many :answers
    belongs_to :user
    # 名前は必須入力かつ20文字以内
    validates :name , length: {  maximum: 20 } , presence: true
    validates :age , numericality: {
            only_integer: true, greater_than_or_equal_to: 0
          }

    # 内容は必須入力かつ2文字以上30文字以下
    validates :body , length: {minimum: 2 , maximum: 140 } , presence: true
    
end

app/models/user.rb
class User < ActiveRecord::Base
    
    has_many :messages
    has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
 before_action :set_answer, only: [:edit, :update, :destroy]
  def index
    @answers = Answer.all
    @answer = Answer.new
    @message = Message.find(params[:id])
  end
  
  def create
    @answer = Answer.new(answer_params)
    if @answer.save
      redirect_to answers_path , notice: 'メッセージを保存しました'
    else
      @answers = Answer.all
      flash.now[:alert] = "メッセージの保存に失敗しました。"
      render 'index'
    end
  end
  
  def edit
  end
  
  def update
    if @answer.update(answer_params)
      redirect_to answers_path , notice: 'メッセージを編集しました'
    else
      render 'edit'
    end
  end
  
   def destroy
    @answer.destroy
    redirect_to answers_path, notice: 'メッセージを削除しました'
   end
  
    
  def show
    @message = Message.find(params[:id])
    @answer = @message.answers.new(answer_params)
    @answer = Answer.find(params[:id])
  end
  

  private
  def answer_params
    params.require(:answer).permit(:name, :age, :body)
  end
  
  def set_answer
    @answer = Answer.find(params[:id])
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:edit, :update, :destroy]
  def index
     # Messageを全て取得する。
    @messages = Message.all
    @message = Message.new
  end
  
  ## ここから追記
  def create
    @message = Message.new(message_params)
    if @message.save
      redirect_to root_path , notice: 'メッセージを保存しました'
    else
      # メッセージが保存できなかった時
      @messages = Message.all
      flash.now[:alert] = "メッセージの保存に失敗しました。"
      render 'index'
    end
  end
  
  def edit
  end
  
  def update
    if @message.update(message_params)
      # 保存に成功した場合はトップページへリダイレクト
      redirect_to root_path , notice: 'メッセージを編集しました'
    else
      # 保存に失敗した場合は編集画面へ戻す
      render 'edit'
    end
  end
  
   def destroy
    @message.destroy
    redirect_to root_path, notice: 'メッセージを削除しました'
   end
  
    
  def show
    @message = Message.find(params[:id])
    @answers = @message.answers
    @answer = Answer.new
  end
  

  private
  def message_params
    params.require(:message).permit(:name, :age, :area, :category, :body)
  end
  ## ここまで
  
  def set_message
    @message = Message.find(params[:id])
  end

  
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/answers/create.html.erb
<h1>Answers#create</h1>
<p>Find me in app/views/answers/create.html.erb</p>

app/views/answers/destroy.html.erb
<h1>Answers#destroy</h1>
<p>Find me in app/views/answers/destroy.html.erb</p>

app/views/answers/edit.html.erb
<h1>Answers#edit</h1>
<p>Find me in app/views/answers/edit.html.erb</p>

app/views/answers/index.html.erb
<div class="panel panel-danger">
    <div class="panel-heading">
      <span class="label label-info"><%= @message.name %></span>
      <span class="label label-default"><%= @message.age %></span>
      </div>
      <div class="panel-body">
      <span class="label label-warning"><%= @message.category %></span>
      <%= @message.body %>
      <br>
      </div>
      </div>

<div class="answer answer-default">
  <div class="answer-heading">
    all answers
  </div>
  
  <div class="answer-body">
    <% @answers.each do |answer| %>
      <span class="label label-info"><%= answer.name %></span>
      <%= answer.body %>
      <br>
    <% end %>
  </div>
</div>
   

<%= form_for(@answer) do |f| %>
  <% if @answer.errors.present? %>
    <div class="alert alert-danger">
      <%= alert %>
      <ul>
        <% @answer.errors.full_messages.each do |full_message| %>
          <li>
            <%= full_message %>
          </li>
        <% end %> 
      </ul>
    </div>
  <% end %>

<div class="form-group">
  <span class="col-sm-2" id="basic-addon1">Name</span>
  <div class="col-sm-10" aria-describedby="basic-addon1">
  <%= f.text_field :name , placeholder: "Pepper", class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <span class="col-sm-2" id="basic-addon1">Age</span>
  <div class="col-sm-10" aria-describedby="basic-addon1">
  <%= f.text_field :age , placeholder: "29", class: "form-control" %>
</div>
</div>

<div class="form-group">
  <span class="col-sm-2" id="basic-addon1">Contents</span>
  <div class="col-sm-10" aria-describedby="basic-addon1">
  <%= f.text_area :body , placeholder: "Which carrier is the best in Japan?", class: "form-control" %>
</div>
</div>

  <div class="col-sm-offset-2 col-sm-10">
  <%= f.submit class: "btn btn-sm btn-primary" %>
  </div>

<% end %>

app/views/answers/new.html.erb
<h1>Answers#new</h1>
<p>Find me in app/views/answers/new.html.erb</p>

app/views/answers/show.html.erb
<h2>Category</h2>
<p><%= @message.category %></p>
<h2>Contents</h2>
<p><%= @message.body %></p>

<div class="answer answer-default">
  <div class="answer-heading">
    all answers
  </div>
 
  <div class="answer-body">
    <% if @message.answers.any? %>
    <% @answers.each do |answer| %>
      <span class="label label-info"><%= answer.name %></span>
      <%= answer.body %>
      <br>
    <% end %>
    <% end %>
  </div>
</div>

<%= form_for(@answer) do |f| %>
  <% if @answer.errors.present? %>
    <div class="alert alert-danger">
      <%= alert %>
      <ul>
        <% @answer.errors.answers.each do |answers| %>
          <li>
            <%= answers %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
  
  <%= f.hidden_field :message_id, :value => "message.id" %>
  
  <span class="col-sm-2" id="basic-addon1">Name</span>
  <div class="col-sm-10" aria-describedby="basic-addon1">
  <%= f.text_field :name , placeholder: "Pepper", class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <span class="col-sm-2" id="basic-addon1">Age</span>
  <div class="col-sm-10" aria-describedby="basic-addon1">
  <%= f.text_field :age , placeholder: "29", class: "form-control" %>
</div>
</div>

<div class="form-group">
  <span class="col-sm-2" id="basic-addon1">Contents</span>
  <div class="col-sm-10" aria-describedby="basic-addon1">
  <%= f.text_area :body , placeholder: "Which carrier is the best in Japan?", class: "form-control" %>
</div>
</div>

  <div class="col-sm-offset-2 col-sm-10">
  <%= f.submit class: "btn btn-sm btn-primary" %>
  </div>

<% end %>

app/views/answers/update.html.erb
<h1>Answers#update</h1>
<p>Find me in app/views/answers/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MessageBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
    <nav class="navbar">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Guidable Q&A</a>
      </div>
    </div>
  </nav>

<div class="container">
    <% if notice %>
      <div class="alert alert-info">
        <%= notice %>
      </div>
    <% end %>
    
    <%= yield %>
  </div>
</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.present? %>
    <div class="alert alert-danger">
      <%= alert %>
      <ul>
        <% @message.errors.full_messages.each do |full_message| %>
          <li>
            <%= full_message %>
          </li>
        <% end %> 
      </ul>
    </div>
  <% end %>

<div class="form-group">
  <span class="col-sm-2" id="basic-addon1">Name</span>
  <div class="col-sm-10" aria-describedby="basic-addon1">
  <%= f.text_field :name , placeholder: "Pepper", class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <span class="col-sm-2" id="basic-addon1">Age</span>
  <div class="col-sm-10" aria-describedby="basic-addon1">
  <%= f.text_field :age , placeholder: "29", class: "form-control" %>
</div>
</div>

<div class="form-group">
  <span class="col-sm-2" id="basic-addon1">Area</span>
  <div class="col-sm-10" aria-describedby="basic-addon1">
  <%= f.text_field :area , placeholder: "Tokyo", class: "form-control" %>
</div>
</div>

<div class="form-group">
  <span class="col-sm-2" id="basic-addon1">Category</span>
  <div class="col-sm-10" aria-describedby="basic-addon1">
  <%= f.text_area :category , placeholder: "Telecommunication", class: "form-control" %>
</div>
</div>

<div class="form-group">
  <span class="col-sm-2" id="basic-addon1">Contents</span>
  <div class="col-sm-10" aria-describedby="basic-addon1">
  <%= f.text_area :body , placeholder: "Which carrier is the best in Japan?", class: "form-control" %>
</div>
</div>

  <div class="col-sm-offset-2 col-sm-10">
  <%= f.submit class: "btn btn-sm btn-primary" %>
  </div>

<% end %>

app/views/messages/_form_answer.html.erb
<%= form_answer_for(@message) do |f| %>
  <% if @message.errors.present? %>
    <div class="alert alert-danger">
      <%= alert %>
      <ul>
        <% @message.errors.full_messages.each do |full_message| %>
          <li>
            <%= full_message %>
          </li>
        <% end %> 
      </ul>
    </div>
  <% end %>

<div class="form-group">
  <span class="col-sm-2" id="basic-addon1">Name</span>
  <div class="col-sm-10" aria-describedby="basic-addon1">
  <%= f.text_field :name , placeholder: "Pepper", class: "form-control" %>
</div>
</div>

<div class="form-group">
  <span class="col-sm-2" id="basic-addon1">Contents</span>
  <div class="col-sm-10" aria-describedby="basic-addon1">
  <%= f.text_area :answer , placeholder: "Softbank is the best. Because...", class: "form-control" %>
</div>
</div>

  <div class="col-sm-offset-2 col-sm-10">
  <%= f.submit class: "btn btn-sm btn-primary" %>
  </div>

<% end %>

app/views/messages/edit.html.erb
<h1>メッセージの編集</h1>

<%= render 'form' %>

app/views/messages/index.html.erb
    <% @messages.each do |message| %>
    <div class="panel panel-danger">
    <div class="panel-heading">
      <span class="label label-info"><%= message.name %></span>
      <span class="label label-default"><%= message.age %></span>
      </div>
      <div class="panel-body">
      <span class="label label-warning"><%= message.category %></span>
      <%= message.body %>
       (<%= link_to "edit" , edit_message_path(message) %>
         <%= link_to "destroy" , message , method: :delete, data: { confirm: '削除してもよろしいですか？' } %>
         <%= link_to "answer" , message_path(message.id) %>
        )
      <br>
      </div>
      </div>
    <% end %>
    <br>
  


<% #部分テンプレートを読み込んでいる %>
<%= render 'form' %>

app/views/messages/show.html.erb
<div class="panel panel-danger">
    <div class="panel-heading">
      <span class="label label-info"><%= @message.name %></span>
      <span class="label label-default"><%= @message.age %></span>
      </div>
      <div class="panel-body">
      <span class="label label-warning"><%= @message.category %></span>
      <%= @message.body %>
      <br>
      </div>
      </div>


    <% if @message.answers.any? %>
    <% @answers.each do |answer| %>
    <div class="panel panel-info">
      <div class="panel-heading">
        <%= answer.name %>
        </div>
         <div class="panel-body">
      <%= answer.body %>
      </div>
      </div>
    <% end %>
    <% end %>


<%= form_for(@answer) do |f| %>
  <% if @answer.errors.present? %>
    <div class="alert alert-danger">
      <%= alert %>
      <ul>
        <% @answer.errors.answers.each do |answers| %>
          <li>
            <%= answers %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
  
  <%= f.hidden_field :message_id, :value => "message.id" %>
  
  <span class="col-sm-2" id="basic-addon1">Name</span>
  <div class="col-sm-10" aria-describedby="basic-addon1">
  <%= f.text_field :name , placeholder: "Pepper", class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <span class="col-sm-2" id="basic-addon1">Age</span>
  <div class="col-sm-10" aria-describedby="basic-addon1">
  <%= f.text_field :age , placeholder: "29", class: "form-control" %>
</div>
</div>

<div class="form-group">
  <span class="col-sm-2" id="basic-addon1">Contents</span>
  <div class="col-sm-10" aria-describedby="basic-addon1">
  <%= f.text_area :body , placeholder: "Which carrier is the best in Japan?", class: "form-control" %>
</div>
</div>

  <div class="col-sm-offset-2 col-sm-10">
  <%= f.submit class: "btn btn-sm btn-primary" %>
  </div>

<% end %>